### ISSUE TITLE
ключики коммитить айайай

### ISSUE THREAD

**Issue by ipsavitsky** [Eive1Me/CowRotator#1]
![image](https://user-images.githubusercontent.com/33558632/171734689-2bf5f6a4-0f79-4162-a866-19ae9e3390dc.png)

ключ закоммичен - надо бы сделать ребейз или ревоук ключа и больше никогда о старом не вспоминать

**Comment by Eive1Me** [comment]
Ревоукнуто и вычеркнуто из памяти
